config/routes.rb
Rails.application.routes.draw do
  root to: "repositories#index"

  get :ping, to: ->(env) { [ "200", { "Content-Type" => "text/plain" }, [ "pong" ] ] }

  get "repo/*repo/tag/*tag",    to: "tags#show",         as: :tag,         constraints: { repo: /.+/, tag: /[^\/]+/ }
  get "repo/*repo",             to: "repositories#show", as: :repository,  constraints: { repo: /.+/ }

  get "*repo:*tag",             to: redirect("repo/%{repo}/tag/%{tag}"),   constraints: { repo: /.+/, tag: /[^\/]+/ }
  get "*repo",                  to: redirect("repo/%{repo}"),              constraints: { repo: /.+/ }

  delete "repo/*repo/tag/*tag", to: "tags#destroy",                        constraints: { repo: /.+/, tag: /[^\/]+/ }
end

app/models/repository.rb
class Repository < Resource
  include ActiveModel::Model

  attr_accessor :name, :tags

  def self.list(count: Rails.configuration.x.catalog_page_size, last: nil)
    response = client.get "/v2/_catalog", { n: count, last: last }.compact
    repositories = response.body["repositories"] || []
    entries  = repositories.map { |name| new(name: name) }

    Collection.new entries: entries, more: response.headers.has_key?("Link")
  end

  def self.find(name)
    begin
      response = client.get "/v2/#{name}/tags/list"
      tags     = response.body["tags"]
    rescue Faraday::ResourceNotFound => e
      tags = nil
    end

    new(
      name: name,
      tags: Array.wrap(tags)
    )
  end

  def namespace(root = "")
    name.split("/").size == 1 ? root : name.split("/")[0...-1].join("/")
  end

  def image
    name.split("/").last
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  helper_method :configs
  helper_method :sort_tags_by
  helper_method :sort_tags_order

  after_action do
    cookies.permanent[:sort_tags_by]    = sort_tags_by
    cookies.permanent[:sort_tags_order] = sort_tags_order
  end

  def index
    @repositories = Repository.list(last: params[:last])
    @namespaces   = Hash[@repositories.group_by(&:namespace).sort]
  end

  def show
    @repository = Repository.find params[:repo]
    @tags       = sort_tags
  end

  private

  def configs
    Rails.application.config.x
  end

  def sort_tags
    tags = @repository.tags
    tags = tags.sort if sort_tags_by == "name"
    tags = VersionSorter.sort(tags) if sort_tags_by == "version"
    tags = tags.reverse if sort_tags_order == "desc"
    tags
  end

  def sort_tags_by
    params[:sort_tags_by] || cookies[:sort_tags_by] || configs.sort_tags_by
  end

  def sort_tags_order
    params[:sort_tags_order] || cookies[:sort_tags_order] || configs.sort_tags_order
  end
end

app/views/repositories/_namespace.html.erb
<div class="row my-4">
  <div class="col-md-12">
    <div class="card card-border-blue">
      <div class="card-header py-0" id="namespace-<%= namespace %>">
        <h4 class="h6 text-muted my-0 mt-3">Namespace</h4>
        <h6 class="h4 mb-3"><%= namespace.presence || "/" %></h6>
      </div>
      <div>
        <ul class="list-group list-group-flush">
          <%= content_tag :div, class: {collapse: configs.collapse_namespaces}, id: "namespace-#{namespace}-repos" do %>
            <% repositories.each do |repository| %>
              <%= render "repository", repository: repository %>
            <% end %>
          <% end %>

          <%= content_tag :button, class: "collapsed btn btn-default w-100", data: {"bs-toggle": "collapse", "bs-target": "#namespace-#{namespace}-repos"} do %>
            <span class="if-collapsed">&hellip;</span>
            <span class="if-not-collapsed">&times;</span>
          <% end if configs.collapse_namespaces %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/repositories/_repository.html.erb
<li class="list-group-item list-group-item-action py-3 item-repository">
  <%= link_to repository_path(repository.name), class: "d-flex align-items-center text-reset text-decoration-none" do %>
    <div class="flex-grow-1">
      <span class="badge">IMG</span>
      <span class="mx-2"><%= repository.image %></span>
    </div>
    <%= image_tag "icons/arrow.png", alt: "&rsaquo;", width: "16" %>
  <% end %>
</li>

app/views/repositories/_sort_links.html.erb
<p class="text-right">
  <small>
    <strong>Sort:</strong> [
      <% {"api" => "API", "name" => "Name", "version" => "Version"}.each do |key, name| %>
        <%= link_to name, {sort_tags_by: key, sort_tags_order: sort_tags_order}, class: class_names("text-reset", {"text-decoration-none": sort_tags_by != key}) %>
      <% end %>
    ]
    <strong>Order:</strong> [
      <% {"asc" => "ASC", "desc" => "DESC"}.each do |key, name| %>
        <%= link_to name, {sort_tags_order: key, sort_tags_by: sort_tags_by}, class: class_names("text-reset", {"text-decoration-none": sort_tags_order != key}) %>
      <% end %>
    ]
  </small>
</p>

app/views/repositories/_tag.html.erb
<li class="list-group-item list-group-item-action py-3 item-tag">
  <%= link_to tag_path(repo: repository.name, tag: tag), class: "d-flex align-items-center text-reset text-decoration-none" do %>
    <div class="flex-grow-1">
      <span class="badge">TAG</span>
      <span class="mx-2"><%= tag %></span>
    </div>
    <%= image_tag "icons/arrow.png", alt: "&rsaquo;", width: "16" %>
  <% end %>
</li>

app/views/repositories/index.html.erb
<% if @repositories.any? %>
  <% @namespaces.each do |namespace, repositories| %>
    <%= render "namespace", namespace: namespace, repositories: repositories %>
  <% end %>

  <% if @repositories.more? %>
    <div class="text-center">
      <%= link_to root_path(last: @repositories.last.name), class: "btn btn-outline-secondary px-4" do %>
        Next page
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="card-body text-center py-5">
    <h2>Empty</h2>
    <h4 class="lead text-muted">There are no repositories in this registry at the moment.</h4>
  </div>
<% end %>

app/views/repositories/show.html.erb
<div class="row my-4">
  <div class="col-md-12">
    <div class="card card-border-blue">
      <div class="card-header py-0">
        <h4 class="h6 text-muted my-0 mt-3">Repository</h4>
        <h6 class="h4 mb-3"><%= @repository.name %></h6>

        <%= render "sort_links" if @tags.size > 1 %>
      </div>
      <% if @tags.any? %>
        <div>
          <ul class="list-group list-group-flush">
            <% @tags.each do |tag| %>
              <%= render "tag", repository: @repository, tag: tag %>
            <% end %>
          </ul>
        </div>
      <% else %>
        <div class="card-body text-center py-5">
          <h2>No tags</h2>
          <h4 class="lead text-muted">No tags are available at the moment.</h4>
        </div>
      <% end %>
    </div>
  </div>
</div>